# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# In root git directory run: pre-commit install.
# Now pre-commit will run automatically on git commit.
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: [--maxkb=1024]
